### PR TITLE
Show defaults to not recurse tree, add print

### LINKED ISSUE #9: function Base.show(io::IO, tree::RTree) prints entire tree, crashes REPL
Hi team,

Wondering if we can discuss the behaviour of https://github.com/alyst/SpatialIndexing.jl/blob/master/src/rtree/show.jl

Specifically: the last line of the show() function, when we have large trees (200k+ nodes) and using this interactively, i have to remember to always suppress the output and never print the object in the REPL, or otherwise it will flood the REPL and i basically have to restart the julia session.
```
function Base.show(io::IO, tree::RTree)
    print(io, typeof(tree))
    print(io, "(variant="); print(io, tree.variant)
    print(io, ", tight_mbrs="); print(io, tree.tight_mbrs)
    print(io, ", nearmin_overlap="); print(io, tree.nearmin_overlap)
    print(io, ", fill_factor="); print(io, tree.fill_factor)
    print(io, ", split_factor="); print(io, tree.split_factor)
    print(io, ", reinsert_factor="); print(io, tree.reinsert_factor)

    print(io, ", leaf_capacity="); print(io, capacity(Leaf, tree))
    print(io, ", branch_capacity="); print(io, capacity(Branch, tree)); println(io, ")")
    print(io, length(tree)); print(io, " element(s) in "); print(io, height(tree));
    print(io, " level(s) ("); print(io, join(reverse(tree.nnodes_perlevel), ", ")); println(io, " node(s) per level):")
    # this line which recursively prints every branch/node
    _show(io, tree.root, recurse=true, indent=1)  end
```

Can we consider having changing this to `print(io::IO, tree::RTree)` and having `show(io::IO, tree::RTree)` without the final recursion call?

That will make working with the RTree interactively much easier, as users can control when they want to print the full tree.

### PR DESCRIPTION
**Pull request by hs-ye**
This small update prevents Rtree objects from recursively printing when they are first created or just called in the REPL, unless the 'print' function is applied to it.

Should fix https://github.com/alyst/SpatialIndexing.jl/issues/9

I've tested it with testing scripts, per below:
```

using SpatialIndexing
using Random, Test

const SI=SpatialIndexing

Random.seed!(32123)
mbrs = Vector{SI.Rect{Float64, 3}}()
for i in 1:1000
    w, h, d = 5 .* rand(3)
    x, y, z = 50 .* randn(3)
    rmbr = SI.Rect((x-w, y-h, z-d), (x+w, y+h, z+d))
    push!(mbrs, rmbr)
end
tree = RTree{SI.dimtype(eltype(mbrs)), ndims(eltype(mbrs))}(Int, String, leaf_capacity = 20, branch_capacity = 20)
@test tree isa RTree{Float64, 3, SpatialElem{Float64, 3, Int, String}}
for (i, rmbr) in enumerate(mbrs)
    insert!(tree, rmbr, i, string(i))
    @test length(tree) == i
    @test tree.nelem_insertions == i
    @test SI.check(tree)
    #@debug "$i: len=$(length(tree)) height=$(SI.height(tree))"
end

tree  # defaults to show
@show tree  # doesn't print entire tree
print(tree)  # prints entire tree recursively
```

### CODE REVIEW

**Comment by alyst** [comment]
Thanks for the PR! The changes look fine.
It's nice that you already have a test script. Could you please make it into the real test? You can print into `IOBuffer` and use `take!()` to get the output as the string that you `@test` against the expected output, and then we should be ready to merge.

File: test/rtree.jl [hunk 1]
```diff
@@ -345,4 +345,36 @@ end
...
+        rmbr = SI.Rect((x-w, y-h, z-d), (x+w, y+h, z+d))
+        push!(mbrs, rmbr)
+    end
+    tree = RTree{SI.dimtype(eltype(mbrs)), ndims(eltype(mbrs))}(Int, String, leaf_capacity = 4, branch_capacity = 4)
+    for (i, rmbr) in enumerate(mbrs)
+        insert!(tree, rmbr, i, string(i))
+    end
+    io = IOBuffer()
+    show(io, tree)
+test_show_string = "RTree{Float64, 3, SpatialElem{Float64, 3, Int64, String}}(variant=RTreeStar, tight_mbrs=true, nearmin_overlap=1, fill_factor=0.7, split_factor=0.4, reinsert_factor=0.3, leaf_capacity=4, branch_capacity=4)
```
Comment (alyst) [inline test/rtree.jl]:
```suggestion
    test_show_string = "RTree{Float64, 3, SpatialElem{Float64, 3, Int64, String}}(variant=RTreeStar, tight_mbrs=true, nearmin_overlap=1, fill_factor=0.7, split_factor=0.4, reinsert_factor=0.3, leaf_capacity=4, branch_capacity=4)
```

File: test/rtree.jl [hunk 2]
```diff
@@ -345,4 +345,36 @@ end
...
+5 element(s) in 2 level(s) (1, 2 node(s) per level):
+ level=2 nchildren=2 mbr=((-59.00467487877491, -106.44985074094573, -1.8124660179176457), (25.194696853584425, 82.01053603165072, 66.15390901881007))"
+    @test String(take!(io)) == test_show_string
+    print(io, tree);
+test_print_string = "RTree{Float64, 3, SpatialElem{Float64, 3, Int64, String}}(variant=RTreeStar, tight_mbrs=true, nearmin_overlap=1, fill_factor=0.7, split_factor=0.4, reinsert_factor=0.3, leaf_capacity=4, branch_capacity=4)
```
Comment (alyst) [inline test/rtree.jl]:
```suggestion
    test_print_string = "RTree{Float64, 3, SpatialElem{Float64, 3, Int64, String}}(variant=RTreeStar, tight_mbrs=true, nearmin_overlap=1, fill_factor=0.7, split_factor=0.4, reinsert_factor=0.3, leaf_capacity=4, branch_capacity=4)
```

File: test/rtree.jl [hunk 3]
```diff
@@ -345,4 +345,36 @@ end
...
+   SpatialElem{Float64, 3, Int64, String}(SpatialIndexing.Rect{Float64, 3}((6.082248036920026, -38.9063486598234, 3.0952063849011457), (12.19631225263875, -30.907320148649454, 11.836599469643247)), 1, \"1\")
+   SpatialElem{Float64, 3, Int64, String}(SpatialIndexing.Rect{Float64, 3}((-45.93785355640892, 16.830752184763824, 6.092707944497514), (-36.84495303140741, 25.500284328833658, 8.730015029362885)), 3, \"3\")
+  level=1 nchildren=2 mbr=((18.96738863622915, 23.453319656407228, 45.836253429373855), (25.194696853584425, 82.01053603165072, 66.15390901881007)):
+   SpatialElem{Float64, 3, Int64, String}(SpatialIndexing.Rect{Float64, 3}((23.64626219966553, 23.453319656407228, 63.51571976040875), (25.194696853584425, 29.654146094557053, 66.15390901881007)), 2, \"2\")
+   SpatialElem{Float64, 3, Int64, String}(SpatialIndexing.Rect{Float64, 3}((18.96738863622915, 78.81466937900943, 45.836253429373855), (19.972567909863624, 82.01053603165072, 48.377916375654976)), 4, \"4\")"
+    @test String(take!(io)) == test_print_string
+end
```
Comment (alyst) [inline test/rtree.jl:388]:
```suggestion
end

```

File: src/rtree/show.jl [hunk 4]
```diff
@@ -35,3 +35,7 @@ function _show(io::IO, node::Node; recurse::Bool=false, indent::Int=0)
         end
     end
 end
+
+function Base.print(io::IO, tree::RTree;)
+    show(io, tree; recurse=true)    
+end
```
Comment (alyst) [inline src/rtree/show.jl]:
```suggestion
end

```

**Comment by alyst** [comment]
Thank you! Just one final touch before I merge it: could you please add the test for explicit `show(..., recurse=true)` and `show(..., recurse=false)`?
You already have the test strings for the expected output, so it should be just about adding a few lines.

File: test/rtree.jl [hunk 5]
```diff
@@ -345,4 +345,37 @@ end
...
+        rmbr = SI.Rect((x-w, y-h, z-d), (x+w, y+h, z+d))
+        push!(mbrs, rmbr)
+    end
+    tree = RTree{SI.dimtype(eltype(mbrs)), ndims(eltype(mbrs))}(Int, String, leaf_capacity = 4, branch_capacity = 4)
+    for (i, rmbr) in enumerate(mbrs)
+        insert!(tree, rmbr, i, string(i))
+    end
+    io = IOBuffer()
+    show(io, tree)
+    test_show_string = "RTree{Float64, 3, SpatialElem{Float64, 3, Int64, String}}(variant=RTreeStar, tight_mbrs=true, nearmin_overlap=1, fill_factor=0.7, split_factor=0.4, reinsert_factor=0.3, leaf_capacity=4, branch_capacity=4)
```
Comment (alyst) [inline test/rtree.jl]:
```suggestion
    test_show_string = "$(typeof(tree))(variant=RTreeStar, tight_mbrs=true, nearmin_overlap=1, fill_factor=0.7, split_factor=0.4, reinsert_factor=0.3, leaf_capacity=4, branch_capacity=4)
```

File: test/rtree.jl [hunk 6]
```diff
@@ -345,4 +345,37 @@ end
...
+5 element(s) in 2 level(s) (1, 2 node(s) per level):
+ level=2 nchildren=2 mbr=((-59.00467487877491, -106.44985074094573, -1.8124660179176457), (25.194696853584425, 82.01053603165072, 66.15390901881007))"
+    @test String(take!(io)) == test_show_string
+    print(io, tree);
+    test_print_string = "RTree{Float64, 3, SpatialElem{Float64, 3, Int64, String}}(variant=RTreeStar, tight_mbrs=true, nearmin_overlap=1, fill_factor=0.7, split_factor=0.4, reinsert_factor=0.3, leaf_capacity=4, branch_capacity=4)
```
Comment (alyst) [inline test/rtree.jl]:
```suggestion
    test_print_string = "$(typeof(tree))(variant=RTreeStar, tight_mbrs=true, nearmin_overlap=1, fill_factor=0.7, split_factor=0.4, reinsert_factor=0.3, leaf_capacity=4, branch_capacity=4)
```

File: test/rtree.jl [hunk 7]
```diff
@@ -345,4 +345,37 @@ end
...
+   SpatialElem{Float64, 3, Int64, String}(SpatialIndexing.Rect{Float64, 3}((-59.00467487877491, -106.44985074094573, -1.8124660179176457), (-50.8616603332421, -97.63484277313019, 0.6994285624414674)), 5, \"5\")
+   SpatialElem{Float64, 3, Int64, String}(SpatialIndexing.Rect{Float64, 3}((6.082248036920026, -38.9063486598234, 3.0952063849011457), (12.19631225263875, -30.907320148649454, 11.836599469643247)), 1, \"1\")
+   SpatialElem{Float64, 3, Int64, String}(SpatialIndexing.Rect{Float64, 3}((-45.93785355640892, 16.830752184763824, 6.092707944497514), (-36.84495303140741, 25.500284328833658, 8.730015029362885)), 3, \"3\")
+  level=1 nchildren=2 mbr=((18.96738863622915, 23.453319656407228, 45.836253429373855), (25.194696853584425, 82.01053603165072, 66.15390901881007)):
+   SpatialElem{Float64, 3, Int64, String}(SpatialIndexing.Rect{Float64, 3}((23.64626219966553, 23.453319656407228, 63.51571976040875), (25.194696853584425, 29.654146094557053, 66.15390901881007)), 2, \"2\")
+   SpatialElem{Float64, 3, Int64, String}(SpatialIndexing.Rect{Float64, 3}((18.96738863622915, 78.81466937900943, 45.836253429373855), (19.972567909863624, 82.01053603165072, 48.377916375654976)), 4, \"4\")"
```
Comment (alyst) [inline test/rtree.jl]:
```suggestion
    eltyp = eltype(tree)
    rectyp = eltype(mbrs)
    test_print_string = "$(typeof(tree))(variant=RTreeStar, tight_mbrs=true, nearmin_overlap=1, fill_factor=0.7, split_factor=0.4, reinsert_factor=0.3, leaf_capacity=4, branch_capacity=4)
5 element(s) in 2 level(s) (1, 2 node(s) per level):
 level=2 nchildren=2 mbr=((-59.00467487877491, -106.44985074094573, -1.8124660179176457), (25.194696853584425, 82.01053603165072, 66.15390901881007)):
  level=1 nchildren=3 mbr=((-59.00467487877491, -106.44985074094573, -1.8124660179176457), (12.19631225263875, 25.500284328833658, 11.836599469643247)):
   $eltyp($rectyp((-59.00467487877491, -106.44985074094573, -1.8124660179176457), (-50.8616603332421, -97.63484277313019, 0.6994285624414674)), 5, \"5\")
   $eltyp($rectyp((6.082248036920026, -38.9063486598234, 3.0952063849011457), (12.19631225263875, -30.907320148649454, 11.836599469643247)), 1, \"1\")
   $eltyp($rectyp((-45.93785355640892, 16.830752184763824, 6.092707944497514), (-36.84495303140741, 25.500284328833658, 8.730015029362885)), 3, \"3\")
  level=1 nchildren=2 mbr=((18.96738863622915, 23.453319656407228, 45.836253429373855), (25.194696853584425, 82.01053603165072, 66.15390901881007)):
   $eltyp($rectyp((23.64626219966553, 23.453319656407228, 63.51571976040875), (25.194696853584425, 29.654146094557053, 66.15390901881007)), 2, \"2\")
   $eltyp($rectyp((18.96738863622915, 78.81466937900943, 45.836253429373855), (19.972567909863624, 82.01053603165072, 48.377916375654976)), 4, \"4\")"
```

**Comment by hs-ye** [comment]
So I've made the updates and also squashed all the commits into a single one, but I see the unit tests are failing for windows 32 bit, and also the print formatting for one of the ubuntu images `RTree{Float64,3,SpatialElem{Float64,3,Int64,String}}` vs `RTree{Float64, 3, SpatialElem{Float64, 3, Int64, String}}`
Might need to rejig the test a little bit so it tests for things like lines of text and specific members in the string, rather than the entire string, I'll do it later tonight

**Comment by alyst** [comment]
>  formatting for one of the ubuntu images RTree{Float64,3,SpatialElem{Float64,3,Int64,String}} vs RTree{Float64, 3, SpatialElem{Float64, 3, Int64, String}}

I think it is the type formatting change introduced by Julia 1.8. Actually I was fixing it earlier today, I guess my changes got overwritten by the squashing. But you still should see them in the comments history. So maybe you can just reintroduce them.

As for the 1.0 failure -- I think it is because of the different random number generator used in the earlier version. Actually, I think we don't need random number generation here -- it introduces the dependency on the exact random sequence across OSes and versions, which is very fragile. I would rather replace it with the hardcoded integer-based coordinates -- this would also shorten the resulting `show()` output by quite a lot.

**Comment by hs-ye** [comment]
> > formatting for one of the ubuntu images RTree{Float64,3,SpatialElem{Float64,3,Int64,String}} vs RTree{Float64, 3, SpatialElem{Float64, 3, Int64, String}}
> 
> I think it is the type formatting change introduced by Julia 1.8. Actually I was fixing it earlier today, I guess my changes got overwritten by the squashing. But you still should see them in the comments history. So maybe you can just reintroduce them.
> 
> As for the 1.0 failure -- I think it is because of the different random number generator used in the earlier version. Actually, I think we don't need random number generation here -- it introduces the dependency on the exact random sequence across OSes and versions, which is very fragile. I would rather replace it with the hardcoded integer-based coordinates -- this would also shorten the resulting `show()` output by quite a lot.

Oh my bad I didn't realise you were also working on it! Yeah I can make those changes and get it back up

File: test/rtree.jl [hunk 8]
```diff
@@ -345,4 +345,43 @@ end
...
+    test_print_string = "$(typeof(tree))(variant=RTreeStar, tight_mbrs=true, nearmin_overlap=1, fill_factor=0.7, split_factor=0.4, reinsert_factor=0.3, leaf_capacity=4, branch_capacity=4)
+5 element(s) in 2 level(s) (1, 2 node(s) per level):
+ level=2 nchildren=2 mbr=((-1.0, -1.0), (2.0, 2.0)):
+  level=1 nchildren=3 mbr=((-1.0, -1.0), (1.0, 1.0)):
+   SpatialElem{Float64, 2, Int64, String}(SpatialIndexing.Rect{Float64, 2}((-1.0, -1.0), (1.0, 1.0)), 2, \"2\")
+   SpatialElem{Float64, 2, Int64, String}(SpatialIndexing.Rect{Float64, 2}((-1.0, 0.0), (1.0, 1.0)), 3, \"3\")
+   SpatialElem{Float64, 2, Int64, String}(SpatialIndexing.Rect{Float64, 2}((0.0, -1.0), (1.0, 1.0)), 4, \"4\")
+  level=1 nchildren=2 mbr=((0.0, 0.0), (2.0, 2.0)):
+   SpatialElem{Float64, 2, Int64, String}(SpatialIndexing.Rect{Float64, 2}((0.0, 0.0), (2.0, 2.0)), 1, \"1\")
+   SpatialElem{Float64, 2, Int64, String}(SpatialIndexing.Rect{Float64, 2}((1.0, 1.0), (2.0, 2.0)), 5, \"5\")"
```
Comment (alyst) [inline test/rtree.jl]:
```suggestion
    eltyp = eltype(tree)
    rectyp = eltype(mbrs)
    test_show_string = "$(typeof(tree))(variant=RTreeStar, tight_mbrs=true, nearmin_overlap=1, fill_factor=0.7, split_factor=0.4, reinsert_factor=0.3, leaf_capacity=4, branch_capacity=4)
5 element(s) in 2 level(s) (1, 2 node(s) per level):
 level=2 nchildren=2 mbr=((-1.0, -1.0), (2.0, 2.0))"
    test_print_string = "$(typeof(tree))(variant=RTreeStar, tight_mbrs=true, nearmin_overlap=1, fill_factor=0.7, split_factor=0.4, reinsert_factor=0.3, leaf_capacity=4, branch_capacity=4)
5 element(s) in 2 level(s) (1, 2 node(s) per level):
 level=2 nchildren=2 mbr=((-1.0, -1.0), (2.0, 2.0)):
  level=1 nchildren=3 mbr=((-1.0, -1.0), (1.0, 1.0)):
   $eltyp($rectyp((-1.0, -1.0), (1.0, 1.0)), 2, \"2\")
   $eltyp($rectyp((-1.0, 0.0), (1.0, 1.0)), 3, \"3\")
   $eltyp($rectyp((0.0, -1.0), (1.0, 1.0)), 4, \"4\")
  level=1 nchildren=2 mbr=((0.0, 0.0), (2.0, 2.0)):
   $eltyp($rectyp((0.0, 0.0), (2.0, 2.0)), 1, \"1\")
   $eltyp($rectyp((1.0, 1.0), (2.0, 2.0)), 5, \"5\")"
```

**Comment by alyst** [comment]
Thank you!
